export const ICON_PATH = {
  CHEVRON: "/icon/chevron.svg",
  BOOKMARK_MENU: "/icon/bookmark_menu.svg",
  HOME: "/icon/home.svg",
  CLOCK: "/icon/clock.svg",
  EDIT: "/icon/edit.svg",
  LOGOUT: "/icon/logout.svg",
  SEARCH: "/icon/search.svg",
  SETTING: "/icon/setting.svg",
  MANAGE: "/icon/manage.svg",
  VIEW: "/icon/view.svg",
  NOTIFICATION: "/icon/notification.svg",
  EXPERIENCE: "/icon/experience.svg",
  REFLECTION: "/icon/reflection.svg",
  INTROSPECTION: "/icon/introspection.svg",
  IMPROVEMENT: "/icon/improvement.svg",
  LESSON: "/icon/lesson.svg",
  DELETE: "/icon/delete.svg",
  FAVORITE: "/icon/favorite.svg",
  BOOKMARK: "/icon/bookmark.svg",
  CLOSE: "/icon/close.svg",
};
